package com.hxh19950701.webviewtvlive

import com.hxh19950701.webviewtvlive.playlist.Channel

val fullChannels = mutableListOf<Channel>()
    .addChannels(
        "央视",
        Channel("CCTV-1", "https://tv.cctv.com/live/cctv1/"),
        Channel("CCTV-2", "https://tv.cctv.com/live/cctv2/"),
        Channel("CCTV-3", "https://tv.cctv.com/live/cctv3/"),
        Channel("CCTV-4", "https://tv.cctv.com/live/cctv4/"),
        Channel("CCTV-5", "https://tv.cctv.com/live/cctv5/"),
        Channel("CCTV-5+", "https://tv.cctv.com/live/cctv5plus/"),
        Channel("CCTV-6", "https://tv.cctv.com/live/cctv6/"),
        Channel("CCTV-7", "https://tv.cctv.com/live/cctv7/"),
        Channel("CCTV-8", "https://tv.cctv.com/live/cctv8/"),
        Channel("CCTV-9", "https://tv.cctv.com/live/cctvjilu/"),
        Channel("CCTV-10", "https://tv.cctv.com/live/cctv10/"),
        Channel("CCTV-11", "https://tv.cctv.com/live/cctv11/"),
        Channel("CCTV-12", "https://tv.cctv.com/live/cctv12/"),
        Channel("CCTV-13", "https://tv.cctv.com/live/cctv13/"),
        Channel("CCTV-14", "https://tv.cctv.com/live/cctv14/"),
        Channel("CCTV-15", "https://tv.cctv.com/live/cctv15/"),
        Channel("CCTV-16", "https://tv.cctv.com/live/cctv16/"),
        Channel("CCTV-17", "https://tv.cctv.com/live/cctv17/"),
        Channel("CCTV-4 欧洲", "https://tv.cctv.com/live/cctveurope/"),
        Channel("CCTV-4 美洲", "https://tv.cctv.com/live/cctvamerica/"),
    )
    .addChannels(
        "湖南",
        Channel("湖南经视", "https://live.mgtv.com/?channelId=280"),
        Channel("湖南电影", "https://live.mgtv.com/?channelId=221"),
        Channel("湖南娱乐", "https://live.mgtv.com/?channelId=344"),
        Channel("湖南都市", "https://live.mgtv.com/?channelId=346"),
        Channel("湖南电视剧", "https://live.mgtv.com/?channelId=484"),
        Channel("湖南国际", "https://live.mgtv.com/?channelId=229"),
        Channel("金鹰卡通", "https://live.mgtv.com/?channelId=287"),
        Channel("金鹰纪实", "https://live.mgtv.com/?channelId=316"),
        Channel("湖南爱晚", "https://live.mgtv.com/?channelId=261"),
        Channel("先锋乒羽", "https://live.mgtv.com/?channelId=329"),
        Channel("快乐垂钓", "https://live.mgtv.com/?channelId=218"),
        Channel("茶频道", "https://live.mgtv.com/?channelId=578"),
        Channel("长沙新闻综合", "https://live.mgtv.com/?channelId=269"),
        Channel("长沙政法", "https://live.mgtv.com/?channelId=254"),
        Channel("长沙女性", "https://live.mgtv.com/?channelId=230"),
    )
    .addChannels(
        "广东",
        Channel("广东卫视", "https://m.gdtv.cn/tvChannelDetail/43"),
        Channel("广东珠江", "https://m.gdtv.cn/tvChannelDetail/44"),
        Channel("广东新闻", "https://m.gdtv.cn/tvChannelDetail/45"),
        Channel("广东民生", "https://m.gdtv.cn/tvChannelDetail/48"),
        Channel("广东体育", "https://m.gdtv.cn/tvChannelDetail/47"),
        Channel("大湾区卫视", "https://m.gdtv.cn/tvChannelDetail/51"),
        Channel("大湾区卫视（海外版）", "https://m.gdtv.cn/tvChannelDetail/46"),
        Channel("经济科教", "https://m.gdtv.cn/tvChannelDetail/49"),
        Channel("广东影视", "https://m.gdtv.cn/tvChannelDetail/53"),
        Channel("4K超高清", "https://m.gdtv.cn/tvChannelDetail/16"),
        Channel("广东少儿", "https://m.gdtv.cn/tvChannelDetail/54"),
        Channel("嘉佳卡通", "https://m.gdtv.cn/tvChannelDetail/66"),
        Channel("岭南戏曲", "https://m.gdtv.cn/tvChannelDetail/15"),
        Channel("现代教育", "https://m.gdtv.cn/tvChannelDetail/13"),
        Channel("荔枝台", "https://m.gdtv.cn/tvChannelDetail/94"),
        Channel("纪录片", "https://m.gdtv.cn/tvChannelDetail/100"),
        Channel("GRTN健康频道", "https://m.gdtv.cn/tvChannelDetail/99"),
        Channel("GRTN文化频道", "https://m.gdtv.cn/tvChannelDetail/75"),
        Channel("GRTN生活频道", "https://m.gdtv.cn/tvChannelDetail/102"),
        Channel("GRTN教育频道", "https://m.gdtv.cn/tvChannelDetail/104"),
        Channel("深圳卫视", "https://www.sztv.com.cn/dianshi.shtml?id=7867"),
        Channel("深圳都市", "https://www.sztv.com.cn/dianshi.shtml?id=7868"),
        Channel("深圳电视剧", "https://www.sztv.com.cn/dianshi.shtml?id=7880"),
        Channel("深圳公共", "https://www.sztv.com.cn/dianshi.shtml?id=7874"),
        Channel("深圳娱乐", "https://www.sztv.com.cn/dianshi.shtml?id=7872"),
        Channel("深圳财经", "https://www.sztv.com.cn/dianshi.shtml?id=7871"),
        Channel("深圳国际", "https://www.sztv.com.cn/dianshi.shtml?id=7944"),
        Channel("深圳少儿", "https://www.sztv.com.cn/dianshi.shtml?id=7881"),
    )
    .addChannels(
        "海外",
        Channel("东森新闻", "https://news.ebc.net.tw/live"),
        Channel("民視第一台", "https://www.4gtv.tv/channel/4gtv-4gtv003?set=4&ch=1"),
        Channel("民視台灣台", "https://www.4gtv.tv/channel/4gtv-4gtv001?set=4&ch=2"),
        Channel("民視", "https://www.4gtv.tv/channel/4gtv-4gtv002?set=4&ch=3"),
        Channel("大愛電視", "https://www.4gtv.tv/channel/4gtv-live007?set=4&ch=209"),
        Channel("中視", "https://www.4gtv.tv/channel/4gtv-4gtv040?set=4&ch=4"),
        Channel("中視經典台", "https://www.4gtv.tv/channel/4gtv-4gtv080?set=4&ch=124"),
        Channel("華視", "https://www.4gtv.tv/channel/4gtv-4gtv041?set=4&ch=6"),
        Channel("三立綜合台", "https://www.4gtv.tv/channel/4gtv-live207?set=4&ch=169"),
        Channel("ARIRANG阿里郎頻道", "https://www.4gtv.tv/channel/4gtv-4gtv079?set=4&ch=189"),
        Channel("DW德国之声", "https://m.dw.com/zh/%E6%AD%A3%E5%9C%A8%E7%9B%B4%E6%92%AD/s-100849"),
        Channel("VOA美国之音", "https://www.voanews.com/live/video/116"),
        Channel("新唐人亚太台", "https://www.ntdtv.com.tw/"),
        Channel("新唐人美东台", "https://www.ntdtv.com/"),
    )