package com.vasthread.webviewtv

import com.vasthread.webviewtv.playlist.Channel

val fullChannels = mutableListOf<Channel>()
    .addChannels(
        "央视",
        Channel("CCTV-1 综合", "", listOf("https://tv.cctv.com/live/cctv1/", "https://www.yangshipin.cn/tv/home?pid=600001859")),
        Channel("CCTV-2 财经", "", listOf("https://tv.cctv.com/live/cctv2/", "https://www.yangshipin.cn/tv/home?pid=600001800")),
        Channel("CCTV-3 综艺", "", listOf("https://tv.cctv.com/live/cctv3/")),
        Channel("CCTV-4 中文国际", "", listOf("https://tv.cctv.com/live/cctv4/", "https://www.yangshipin.cn/tv/home?pid=600001814")),
        Channel("CCTV-5 体育", "", listOf("https://tv.cctv.com/live/cctv5/")),
        Channel("CCTV-5+ 体育赛事", "", listOf("https://tv.cctv.com/live/cctv5plus/")),
        Channel("CCTV-6 电影", "", listOf("https://tv.cctv.com/live/cctv6/")),
        Channel("CCTV-7 国防军事", "", listOf("https://tv.cctv.com/live/cctv7/", "https://www.yangshipin.cn/tv/home?pid=600004092")),
        Channel("CCTV-8 电视剧", "", listOf("https://tv.cctv.com/live/cctv8/")),
        Channel("CCTV-9 记录", "", listOf("https://tv.cctv.com/live/cctvjilu/", "https://www.yangshipin.cn/tv/home?pid=600004078")),
        Channel("CCTV-10 科教", "", listOf("https://tv.cctv.com/live/cctv10/", "https://www.yangshipin.cn/tv/home?pid=600001805")),
        Channel("CCTV-11 戏曲", "", listOf("https://tv.cctv.com/live/cctv11/", "https://www.yangshipin.cn/tv/home?pid=600001806")),
        Channel("CCTV-12 社会与法", "", listOf("https://tv.cctv.com/live/cctv12/", "https://www.yangshipin.cn/tv/home?pid=600001807")),
        Channel("CCTV-13 新闻", "", listOf("https://tv.cctv.com/live/cctv13/", "https://www.yangshipin.cn/tv/home?pid=600001811")),
        Channel("CCTV-14 少儿", "", listOf("https://tv.cctv.com/live/cctvchild/", "https://www.yangshipin.cn/tv/home?pid=600001809")),
        Channel("CCTV-15 音乐", "", listOf("https://tv.cctv.com/live/cctv15/", "https://www.yangshipin.cn/tv/home?pid=600001815")),
        Channel("CCTV-16 奥林匹克", "", listOf("https://tv.cctv.com/live/cctv16/", "https://www.yangshipin.cn/tv/home?pid=600098637")),
        Channel("CCTV-17 农业农村", "", listOf("https://tv.cctv.com/live/cctv17/", "https://www.yangshipin.cn/tv/home?pid=600001810")),
        Channel("CCTV-4 中文国际（欧洲）", "", listOf("https://tv.cctv.com/live/cctveurope/")),
        Channel("CCTV-4 中文国际（美洲）", "", listOf("https://tv.cctv.com/live/cctvamerica/")),
        Channel("CCTV-4K 超高清", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002264")),
        Channel("CETV-1 综合教育", "", listOf("https://tv.gxtv.cn/channel/channelivePlay_ffa6b6e1b32b4a16a73eb3ef66f8bfc7.html")),
        Channel("CETV-2 空中课堂", "", listOf("https://tv.gxtv.cn/channel/channelivePlay_80d0ffb42c114eaf9663708629ff0a3e.html")),
        Channel("CETV-4 职业教育", "", listOf("https://tv.gxtv.cn/channel/channelivePlay_67eace939278435bb4bca90800fb4225.html", "https://edu.cctv.com/cetv/")),
        Channel("CGTN", "", listOf("https://www.yangshipin.cn/tv/home?pid=600014550")),
        Channel("CGTN Español", "", listOf("https://www.yangshipin.cn/tv/home?pid=600084744")),
        Channel("CGTN Français", "", listOf("https://www.yangshipin.cn/tv/home?pid=600084704")),
        Channel("CGTN العربية", "", listOf("https://www.yangshipin.cn/tv/home?pid=600084782")),
        Channel("CGTN Русский", "", listOf("https://www.yangshipin.cn/tv/home?pid=600084758")),
        Channel("CGTN Documentary", "", listOf("https://www.yangshipin.cn/tv/home?pid=600084781")),
    )
    .addChannels(
        "卫视",
        Channel("北京卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002309")),
        Channel("江苏卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002521")),
        Channel("东方卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002483")),
        Channel("浙江卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002520")),
        Channel("湖南卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002475")),
        Channel("湖北卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002508")),
        Channel("广东卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002485")),
        Channel("广西卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002509")),
        Channel("黑龙江卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002498")),
        Channel("海南卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002506")),
        Channel("重庆卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002531")),
        Channel("深圳卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002481")),
        Channel("四川卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002516")),
        Channel("河南卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002525")),
        Channel("东南卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002484")),
        Channel("贵州卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002490")),
        Channel("江西卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002503")),
        Channel("辽宁卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002505")),
        Channel("安徽卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002532")),
        Channel("河北卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002493")),
        Channel("山东卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002513")),
        //Channel("吉林卫视", "", listOf("https://www.jlntv.cn/tv?id=104")),
        Channel("延边卫视", "", listOf("https://www.yb983.com/cys/index.html")),
        Channel("新疆卫视", "", listOf("https://www.xjtvs.com.cn/column/tv/434?channelId=1")),
        Channel("大湾区卫视", "", listOf("https://m.gdtv.cn/tvChannelDetail/51")),
        Channel("大湾区卫视（海外版）", "", listOf("https://m.gdtv.cn/tvChannelDetail/46")),
    )
    .addChannels(
        "湖南",
        Channel("湖南卫视", "", listOf("https://www.yangshipin.cn/tv/home?pid=600002475")),
        Channel("湖南经视", "", listOf("https://live.mgtv.com/?channelId=280")),
        Channel("湖南电影", "", listOf("https://live.mgtv.com/?channelId=221")),
        Channel("湖南娱乐", "", listOf("https://live.mgtv.com/?channelId=344")),
        Channel("湖南都市", "", listOf("https://live.mgtv.com/?channelId=346")),
        Channel("湖南电视剧", "", listOf("https://live.mgtv.com/?channelId=484")),
        Channel("湖南国际", "", listOf("https://live.mgtv.com/?channelId=229")),
        Channel("金鹰卡通", "", listOf("https://live.mgtv.com/?channelId=287")),
        Channel("金鹰纪实", "", listOf("https://live.mgtv.com/?channelId=316")),
        Channel("湖南爱晚", "", listOf("https://live.mgtv.com/?channelId=261")),
        Channel("先锋乒羽", "", listOf("https://live.mgtv.com/?channelId=329")),
        Channel("快乐垂钓", "", listOf("https://live.mgtv.com/?channelId=218")),
        Channel("茶频道", "", listOf("https://live.mgtv.com/?channelId=578")),
        Channel("长沙新闻综合", "", listOf("https://live.mgtv.com/?channelId=269")),
        Channel("长沙政法", "", listOf("https://live.mgtv.com/?channelId=254")),
    )
    .addChannels(
        "广东",
        Channel("广东卫视", "", listOf("https://m.gdtv.cn/tvChannelDetail/43")),
        Channel("广东珠江", "", listOf("https://m.gdtv.cn/tvChannelDetail/44")),
        Channel("广东新闻", "", listOf("https://m.gdtv.cn/tvChannelDetail/45")),
        Channel("广东民生", "", listOf("https://m.gdtv.cn/tvChannelDetail/48")),
        Channel("广东体育", "", listOf("https://m.gdtv.cn/tvChannelDetail/47")),
        Channel("大湾区卫视", "", listOf("https://m.gdtv.cn/tvChannelDetail/51")),
        Channel("大湾区卫视（海外版）", "", listOf("https://m.gdtv.cn/tvChannelDetail/46")),
        Channel("经济科教", "", listOf("https://m.gdtv.cn/tvChannelDetail/49")),
        Channel("广东影视", "", listOf("https://m.gdtv.cn/tvChannelDetail/53")),
        Channel("4K超高清","", listOf( "https://m.gdtv.cn/tvChannelDetail/16")),
        Channel("广东少儿", "", listOf("https://m.gdtv.cn/tvChannelDetail/54")),
        Channel("嘉佳卡通", "", listOf("https://m.gdtv.cn/tvChannelDetail/66")),
        Channel("岭南戏曲", "", listOf("https://m.gdtv.cn/tvChannelDetail/15")),
        Channel("现代教育", "", listOf("https://m.gdtv.cn/tvChannelDetail/13")),
        Channel("荔枝台", "", listOf("https://m.gdtv.cn/tvChannelDetail/94")),
        Channel("纪录片", "", listOf("https://m.gdtv.cn/tvChannelDetail/100")),
        Channel("GRTN健康频道", "", listOf("https://m.gdtv.cn/tvChannelDetail/99")),
        Channel("GRTN文化频道", "", listOf("https://m.gdtv.cn/tvChannelDetail/75")),
        Channel("GRTN生活频道", "", listOf("https://m.gdtv.cn/tvChannelDetail/102")),
        Channel("GRTN教育频道", "", listOf("https://m.gdtv.cn/tvChannelDetail/104")),
        Channel("深圳卫视", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7867")),
        Channel("深圳都市", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7868")),
        Channel("深圳电视剧", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7880")),
        Channel("深圳财经", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7871")),
        Channel("深圳国际", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7944")),
        Channel("深圳少儿", "", listOf("https://www.sztv.com.cn/pindao/index.html?id=7881")),
    )
    .addChannels(
        "江西",
        Channel("江西卫视", "", listOf("https://www.jxntv.cn/live/#/")),
        Channel("江西都市", "", listOf("https://www.jxntv.cn/live/#/jxtv2")),
        Channel("江西经济生活", "", listOf("https://www.jxntv.cn/live/#/jxtv3")),
        Channel("江西影视旅游", "", listOf("https://www.jxntv.cn/live/#/jxtv4")),
        Channel("江西公共农业", "", listOf("https://www.jxntv.cn/live/#/jxtv5")),
        Channel("江西少儿", "", listOf("https://www.jxntv.cn/live/#/jxtv6")),
        Channel("江西新闻", "", listOf("https://www.jxntv.cn/live/#/jxtv7")),
        Channel("江西移动", "", listOf("https://www.jxntv.cn/live/#/jxtv8")),
    )
    .addChannels(
        "江苏",
        Channel("江苏卫视", "", listOf("https://live.jstv.com/?channelId=534")),
        Channel("江苏城市", "", listOf("https://live.jstv.com/?channelId=535")),
        Channel("江苏综艺", "", listOf("https://live.jstv.com/?channelId=556")),
        Channel("江苏影视", "", listOf("https://live.jstv.com/?channelId=542")),
        Channel("江苏新闻", "", listOf("https://live.jstv.com/?channelId=536")),
        Channel("江苏教育", "", listOf("https://live.jstv.com/?channelId=545")),
        Channel("江苏体育", "", listOf("https://live.jstv.com/?channelId=537")),
        Channel("江苏国际", "", listOf("https://live.jstv.com/?channelId=544")),
        Channel("优漫卡通", "", listOf("https://live.jstv.com/?channelId=543")),
    )
    .addChannels(
        "上海",
        Channel("东方卫视", "", listOf("https://live.kankanews.com/huikan")),
        Channel("新闻综合", "", listOf("https://live.kankanews.com/huikan?id=2")),
        Channel("外语频道", "", listOf("https://live.kankanews.com/huikan?id=3")),
        Channel("都市频道", "", listOf("https://live.kankanews.com/huikan?id=4")),
        Channel("第一财经", "", listOf("https://live.kankanews.com/huikan?id=5")),
        Channel("纪实人文", "", listOf("https://live.kankanews.com/huikan?id=6")),
        Channel("哈哈炫动", "", listOf("https://live.kankanews.com/huikan?id=9")),
    )
    .addChannels(
        "吉林",
        //Channel("吉林卫视", "", listOf("https://www.jlntv.cn/tv?id=104")),
        Channel("延边卫视", "", listOf("https://www.yb983.com/cys/index.html")),
        Channel("延边朝鲜语综合频道", "", listOf("https://www.yb983.com/ybtv1/index.html")),
        Channel("延边汉语综合频道", "", listOf("https://www.yb983.com/ybtv2/index.html")),
    )
    .addChannels(
        "香港",
        Channel("翡翠台", "", listOf("https://www.tiantianzhibo.net/player/index?id=714fQdFOPs7fA2to6CG0UroN9l0YvCP5kVSLYnbvT654w1jlNQ","https://enz.gdplayertv.to/live-tv/tvb-jade/?embed=1")),
        Channel("無線新聞", "", listOf("https://www.tiantianzhibo.net/player/index?id=5e2avMI8JXyPe9rVuDSxwiCvsqAqCrPBqPsUSWrXDKN2L9rIzA","https://enz.gdplayertv.to/live-tv/tvb-news/?embed=1")),
        Channel("明珠台", "", listOf("https://www.tiantianzhibo.net/player/index?id=910drXCXuvox1KxMaCzEhMltq5JK1qSQy9zm-nkstsFwqLSw7i4","https://idx.gdplayertv.to/live-tv/tvb-pearl/?embed=1")),
        Channel("鳳凰衛視資訊台", "", listOf("https://www.fengshows.com/live")),
        Channel("香港衛視", "", listOf("http://zhibo.hkstv.tv/livestream/mutfysrq/playlist.m3u8", "http://www.hkstv.tv/index/live.html")),
    )
    .addChannels(
        "澳門",
        Channel("澳視澳門", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=1&type=tv", "http://61.244.22.5/ch1/ch1.live/index.m3u8")),
        Channel("澳視葡文", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=2&type=tv")),
        Channel("澳門資訊", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=5&type=tv", "http://61.244.22.5/ch5/info_ch5.live/master.m3u8")),
        Channel("澳門體育", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=6&type=tv")),
        Channel("澳門綜藝", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=7&type=tv")),
        Channel("澳門MACAU", "", listOf("https://www.tdm.com.mo/zh-hant/live?Channel=8&type=tv", "http://61.244.22.5/ch3/ch3.live/index.m3u8")),
    )
    .addChannels(
        "台灣",
        Channel("東森新聞", "", listOf("https://www.tiantianzhibo.net/player/index?id=d7c9cqojVv8HhOKJ21KwZvsYwApfnEiecpCVhysKZsYsWnGGTw", "https://www.4gtv.tv/channel/4gtv-4gtv152?set=4&ch=292")),
        Channel("東森財經", "", listOf("https://www.tiantianzhibo.net/player/index?id=5440lDG41CDeziB7SsRoChqYyIiSs14oznWXOe6Pw3W09l32yA")),
        Channel("東森綜合", "", listOf("https://www.tiantianzhibo.net/player/index?id=f352Z9Iib4gt-4o-2JdjxD-Lcal2DNVSdFv8_KgVIpNEjBnMBA")),
        Channel("東森電影", "", listOf("https://www.tiantianzhibo.net/player/index?id=faffRjOxK2m5W8AzdGxiWAst6NK0Bly9HTgNJP0Ni7KyWlF7tg")),
        Channel("東森戲劇", "", listOf("https://www.tiantianzhibo.net/player/index?id=0ba9U596e_liclHp-sRJyA497-B-o2Ff0ws_6SUz1Yv4ZDBsiQ")),
        Channel("東森洋片", "", listOf("https://www.tiantianzhibo.net/player/index?id=b731J0NuKSooz1MrvfF8lT9CFViu_ykbNOdGI7OkFYK7BbBy3A")),
        Channel("東森幼幼", "", listOf("https://www.tiantianzhibo.net/player/index?id=8d89ITGSf0YWWa2GH1gY2jel3z4ciyTwW2dZKbQq43ZUD73YCg")),
        Channel("年代新聞", "", listOf("https://www.tiantianzhibo.net/player/index?id=0c771kC3czYydY-9dMP-8087HfO99F_8NiDCWRdINHu9FLGGSQ")),
        Channel("民視第一台", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv003?set=4&ch=1")),
        Channel("民視台灣台", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv001?set=4&ch=2")),
        Channel("民視新聞台", "", listOf("https://www.4gtv.tv/channel/litv-ftv13?set=4&ch=31")),
        Channel("民視綜藝台", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv004?set=4&ch=16")),
        Channel("民視旅遊台", "", listOf("https://www.4gtv.tv/channel/litv-ftv07?set=4&ch=61")),
        Channel("民視影劇台", "", listOf("https://www.4gtv.tv/channel/litv-ftv09?set=4&ch=24")),
        Channel("民視", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv002?set=4&ch=3")),
        Channel("中視", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv040?set=4&ch=4")),
        Channel("中視經典台", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv080?set=4&ch=124")),
        Channel("華視", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv041?set=4&ch=6")),
        Channel("華視新聞", "", listOf("https://www.4gtv.tv/channel/4gtv-live014?set=4&ch=273")),
        Channel("大愛電視", "", listOf("https://www.4gtv.tv/channel/4gtv-live007?set=4&ch=209")),
        Channel("ARIRANG阿里郎頻道", "", listOf("https://www.4gtv.tv/channel/4gtv-4gtv079?set=4&ch=189")),
        Channel("原住民族電視台", "", listOf("https://www.4gtv.tv/channel/4gtv-live014?set=4&ch=273")),
    )
    .addChannels(
        "海外",
        Channel("新唐人亚太台", "", listOf("https://www.ntdtv.com.tw/")),
        Channel("新唐人美东台", "", listOf("https://www.ntdtv.com/")),
        Channel("VOA English TV", "", listOf("https://www.voanews.com/live/video/116")),
        Channel("VOA LIVE", "", listOf("https://www.voanews.com/live/video/126")),
    )